#!/usr/bin/env python3
"""Recover the SM4 master key MK that generates RK_B1 via standard SM4 key schedule.

Standard SM4 key schedule:
  K[0..3] = MK[0..3] ^ FK[0..3]
  K[i+4] = K[i] ^ L'(sbox_word(K[i+1] ^ K[i+2] ^ K[i+3] ^ CK[i]))
  rk[i] = K[i+4]

Inverting: K[i] = rk[i-4] ... wait, K[i+4] = K[i] ^ T'(...)
So K[i] = K[i+4] ^ T'(K[i+1] ^ K[i+2] ^ K[i+3] ^ CK[i])

Given rk[0..31], we know K[4..35]. Then we can recover K[3], K[2], K[1], K[0]
by working backward.
  K[i] = K[i+4] ^ T'(K[i+1] ^ K[i+2] ^ K[i+3] ^ CK[i])
For i=3: K[3] = K[7] ^ T'(K[4] ^ K[5] ^ K[6] ^ CK[3])
For i=2: K[2] = K[6] ^ T'(K[3] ^ K[4] ^ K[5] ^ CK[2])
For i=1: K[1] = K[5] ^ T'(K[2] ^ K[3] ^ K[4] ^ CK[1])
For i=0: K[0] = K[4] ^ T'(K[1] ^ K[2] ^ K[3] ^ CK[0])

Then MK[i] = K[i] ^ FK[i].
"""
import sys
sys.path.insert(0, '/mnt/data1/wuql/services/ntqq-sign-server')
import pure_cipher
MASK = 0xFFFFFFFF
def rotl(x, n): return ((x << n) | (x >> (32-n))) & MASK


FK = [0xa3b1bac6, 0x56aa3350, 0x677d9197, 0xb27022dc]
CK_BYTES = [(i*7) & 0xff for i in range(128)]
CK = [int.from_bytes(bytes(CK_BYTES[i*4:i*4+4]), 'big') for i in range(32)]

def L_prime(x):
    return (x ^ rotl(x, 13) ^ rotl(x, 23)) & MASK


def T_prime(x):
    return L_prime(pure_cipher.sbox_word(x))


# Given rk[0..31], recover MK
def recover_mk(rk):
    # K[i+4] = rk[i] for i=0..31, so K[4..35] is known
    K = [None] * 36
    for i in range(32):
        K[i+4] = rk[i]
    # Recover K[3], K[2], K[1], K[0] using:
    # K[i] = K[i+4] ^ T'(K[i+1] ^ K[i+2] ^ K[i+3] ^ CK[i])
    for i in range(3, -1, -1):
        K[i] = K[i+4] ^ T_prime(K[i+1] ^ K[i+2] ^ K[i+3] ^ CK[i])
        K[i] &= MASK
    MK = [K[i] ^ FK[i] for i in range(4)]
    return MK


# Forward to verify
def sm4_ks(MK):
    K = [MK[i] ^ FK[i] for i in range(4)]
    rk = []
    for i in range(32):
        K_next = K[i] ^ T_prime(K[i+1] ^ K[i+2] ^ K[i+3] ^ CK[i])
        K.append(K_next & MASK)
        rk.append(K[i+4])
    return rk


# Try recovery for RK_B1
MK = recover_mk(pure_cipher.RK_B1)
print(f"Recovered MK from RK_B1: {[hex(x) for x in MK]}")

# Verify by re-deriving RK_B1
rk_check = sm4_ks(MK)
print(f"RK_B1 match: {rk_check == list(pure_cipher.RK_B1)}")

# Convert MK to bytes
mk_bytes = b''.join(m.to_bytes(4, 'big') for m in MK)
print(f"MK as bytes (BE): {mk_bytes.hex()}")
mk_bytes_le = b''.join(m.to_bytes(4, 'little') for m in MK)
print(f"MK as bytes (LE): {mk_bytes_le.hex()}")

# Try the same for RK_B2
MK_b2 = recover_mk(pure_cipher.RK_B2)
print(f"\nRecovered MK from RK_B2: {[hex(x) for x in MK_b2]}")
rk_check_b2 = sm4_ks(MK_b2)
print(f"RK_B2 match: {rk_check_b2 == list(pure_cipher.RK_B2)}")
mk_b2_bytes = b''.join(m.to_bytes(4, 'big') for m in MK_b2)
print(f"MK_B2 as bytes (BE): {mk_b2_bytes.hex()}")

# What's in MK_B1?
# The recovered values should match a meaningful input if SM4 KS is being used
print("\n=== Check if MK_B1 looks like MD5 of something ===")
import hashlib
candidates = [
    b"wtlogin.login",
    b"wtlogin.login\x00",
    b"NTQQ",
    b"qq",
    b"\x9a\x4c\x9b\x68\x37\x84\xa8\x91" * 2,  # random
]
for c in candidates:
    if hashlib.md5(c).digest() == mk_bytes:
        print(f"  MD5({c}) == MK!")

# Also check if MK is human-readable or contains patterns
print(f"\nMK_B1 bytes: {mk_bytes}")
print(f"MK_B2 bytes: {mk_b2_bytes}")

# Try if our cipher uses standard SM4 L' or different L
# Hypothesis: if RK_B1 was generated by standard SM4 KS, recovery should work.
# If recovery doesn't reproduce RK_B1, then our cipher uses a non-standard KS.
